Repository gazebosim/gz-physics, pull requests merged in 2020-09, with the labels that each got.

#99 2 ➡️ 3
  codecov.yml
  tools/code_check.sh
  tpe/lib/CMakeLists.txt
  tpe/lib/src/AABBTree.cc
  tpe/lib/src/AABBTree.hh
  tpe/lib/src/AABBTree_TEST.cc
  tpe/lib/src/CollisionDetector.cc
  tpe/lib/src/CollisionDetector.hh
  tpe/lib/src/CollisionDetector_TEST.cc
  tpe/lib/src/Entity.cc
  tpe/lib/src/Entity.hh
  tpe/lib/src/Model.cc
  tpe/lib/src/World.cc
  tpe/lib/src/aabb_tree/AABB.cc
  tpe/lib/src/aabb_tree/AABB.h
  tpe/lib/src/aabb_tree/LICENSE
  tpe/plugin/src/SimulationFeatures.cc
Labels: beta, 🔮 dome

#86 Add support for nested models in TPE
  CMakeLists.txt
  dartsim/src/SDFFeatures.cc
  sdf/include/ignition/physics/sdf/ConstructModel.hh
  sdf/include/ignition/physics/sdf/ConstructNestedModel.hh
  tpe/lib/src/Model.cc
  tpe/lib/src/Model.hh
  tpe/lib/src/Model_TEST.cc
  tpe/plugin/src/Base.hh
  tpe/plugin/src/FreeGroupFeatures.cc
  tpe/plugin/src/SDFFeatures.cc
  tpe/plugin/src/SDFFeatures.hh
  tpe/plugin/src/SDFFeatures_TEST.cc
  tpe/plugin/worlds/nested_model.world
Labels: TPE, 🏰 citadel

#56 Set slip compliance
  dartsim/src/SDFFeatures.cc
  dartsim/src/ShapeFeatures.cc
  dartsim/src/ShapeFeatures.hh
  dartsim/src/ShapeFeatures_TEST.cc
  dartsim/worlds/slip_compliance.sdf
  include/ignition/physics/Shape.hh
  include/ignition/physics/detail/Shape.hh
Labels: enhancement, 📜 blueprint

#101 Preparing for 1.9.0 release
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#102 1 ➡️ 2
  Changelog.md
  dartsim/src/ShapeFeatures.cc
  dartsim/src/ShapeFeatures.hh
  dartsim/src/ShapeFeatures_TEST.cc
  dartsim/worlds/slip_compliance.sdf
  include/ignition/physics/Shape.hh
  include/ignition/physics/detail/Shape.hh
Labels: 🏰 citadel

#107 Bumped examples to ign-physics3
  examples/hello_world_loader/CMakeLists.txt
  examples/hello_world_plugin/CMakeLists.txt
Labels: 🔮 dome

#110 Update readme
  README.md
Labels: 🔮 dome

#111 Tutorial tweaks
  tutorials/01_intro.md
  tutorials/02_installation.md
  tutorials/03_physics_plugins.md
Labels: 🔮 dome

#112 Fix code snippet rendering
  tutorials/02_installation.md
Labels: 🔮 dome
