Repository gazebosim/gz-physics, pull requests merged in 2020-08, with the labels that each got.

#90 2 ➡️ 3
  Changelog.md
  dartsim/src/SimulationFeatures.cc
  dartsim/src/SimulationFeatures_TEST.cc
  dartsim/worlds/contact.sdf
  include/ignition/physics/GetContacts.hh
  include/ignition/physics/SpecifyData.hh
  include/ignition/physics/detail/GetContacts.hh
  include/ignition/physics/detail/PrivateSpecifyData.hh
  include/ignition/physics/detail/SpecifyData.hh
  src/CompositeData.cc
  src/SpecifyData_TEST.cc
  tpe/lib/CMakeLists.txt
  tpe/lib/src/Collision.cc
  tpe/lib/src/Collision.hh
  tpe/lib/src/CollisionDetector.cc
  tpe/lib/src/Collision_TEST.cc
  tpe/lib/src/Entity.cc
  tpe/lib/src/Entity.hh
  tpe/lib/src/Link.cc
  tpe/lib/src/Link_TEST.cc
  tpe/lib/src/Model.cc
  tpe/lib/src/Model_TEST.cc
  tpe/plugin/src/EntityManagementFeatures.cc
  tpe/plugin/src/EntityManagementFeatures.hh
  tpe/plugin/src/FreeGroupFeatures.cc
  tpe/plugin/src/KinematicsFeatures.cc
  tpe/plugin/src/SDFFeatures.cc
  tpe/plugin/src/SDFFeatures.hh
  tpe/plugin/src/SDFFeatures_TEST.cc
  tpe/plugin/src/SimulationFeatures_TEST.cc
  tpe/plugin/worlds/shapes_bitmask.sdf
Labels: 🔮 dome

#91 Update actions CI
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
Labels: 📜 blueprint

#92 1 ➡️ 2
  .github/ci-focal/before_cmake.sh
  .github/ci/packages-bionic.apt
  .github/ci/packages-focal.apt
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
  Changelog.md
  dartsim/CMakeLists.txt
  dartsim/src/JointFeatures.cc
  dartsim/src/SDFFeatures_TEST.cc
Labels: 🏰 citadel

#93 Add profiler code to TPE
  tpe/lib/src/CollisionDetector.cc
  tpe/lib/src/Model.cc
  tpe/lib/src/World.cc
  tpe/plugin/src/SimulationFeatures.cc
Labels: TPE, 🏰 citadel

#94 2 ➡️ 3
  .github/ci-focal/before_cmake.sh
  .github/ci/packages-bionic.apt
  .github/ci/packages-focal.apt
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
  Changelog.md
  dartsim/CMakeLists.txt
  dartsim/src/JointFeatures.cc
  dartsim/src/SDFFeatures_TEST.cc
Labels: 🔮 dome

#95 Removed repeated installation instructions
  README.md
  tutorials/02_installation.md
Labels: documentation, 🔮 dome

#97 Integrate AABB tree for collision checking in TPE
  codecov.yml
  tools/code_check.sh
  tpe/lib/CMakeLists.txt
  tpe/lib/src/AABBTree.cc
  tpe/lib/src/AABBTree.hh
  tpe/lib/src/AABBTree_TEST.cc
  tpe/lib/src/CollisionDetector.cc
  tpe/lib/src/CollisionDetector.hh
  tpe/lib/src/CollisionDetector_TEST.cc
  tpe/lib/src/Entity.cc
  tpe/lib/src/Entity.hh
  tpe/lib/src/Model.cc
  tpe/lib/src/World.cc
  tpe/lib/src/aabb_tree/AABB.cc
  tpe/lib/src/aabb_tree/AABB.h
  tpe/lib/src/aabb_tree/LICENSE
Labels: TPE, 🏰 citadel
