Repository gazebosim/gz-physics, pull requests merged in 2020-07, with the labels that each got.

#69 [Citadel][TPE] Implement collision filtering using collide bitmasks and add CollisionFilterMaskFeature
  tpe/lib/src/Collision.cc
  tpe/lib/src/Collision.hh
  tpe/lib/src/CollisionDetector.cc
  tpe/lib/src/Collision_TEST.cc
  tpe/lib/src/Entity.cc
  tpe/lib/src/Entity.hh
  tpe/lib/src/Link.cc
  tpe/lib/src/Model.cc
  tpe/lib/src/Model_TEST.cc
  tpe/plugin/src/EntityManagementFeatures.cc
  tpe/plugin/src/EntityManagementFeatures.hh
  tpe/plugin/src/SDFFeatures.cc
  tpe/plugin/src/SDFFeatures.hh
  tpe/plugin/src/SimulationFeatures_TEST.cc
  tpe/plugin/worlds/shapes_bitmask.sdf
Labels: 🏰 citadel, 🔮 dome

#40 Extend contact data with force, normal, and penetration depth
  dartsim/src/SimulationFeatures.cc
  dartsim/src/SimulationFeatures_TEST.cc
  dartsim/worlds/contact.sdf
  include/ignition/physics/GetContacts.hh
  include/ignition/physics/detail/GetContacts.hh
Labels: 🏰 citadel, 🔮 dome

#79 Add offset to link and collision pose
  tpe/lib/CMakeLists.txt
  tpe/lib/src/Collision_TEST.cc
  tpe/lib/src/Entity.cc
  tpe/lib/src/Entity.hh
  tpe/lib/src/Link_TEST.cc
  tpe/lib/src/Model_TEST.cc
Labels: TPE, 🏰 citadel

#83 Add link offset to simulation
  tpe/lib/src/Collision_TEST.cc
  tpe/lib/src/Entity.cc
  tpe/lib/src/Link_TEST.cc
  tpe/plugin/src/FreeGroupFeatures.cc
  tpe/plugin/src/KinematicsFeatures.cc
  tpe/plugin/src/SDFFeatures.cc
  tpe/plugin/src/SDFFeatures_TEST.cc
  tpe/plugin/src/SimulationFeatures_TEST.cc
Labels: TPE, 🏰 citadel

#85 Bump to SDFormat 10 for Dome
  .github/workflows/ci-bionic.yml
  CMakeLists.txt
  bitbucket-pipelines.yml
Labels: 🔮 dome

#89 ⬆️ 2.2.0
  CMakeLists.txt
  Changelog.md
  tpe/lib/src/Collision_TEST.cc
  tpe/plugin/src/SDFFeatures.cc
  tpe/plugin/src/SDFFeatures_TEST.cc
Labels: 🏰 citadel
