Repository gazebosim/gz-physics, pull requests merged in 2020-10, with the labels that each got.

#108 ⬆️ 2.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#106 Tutorial ign-physics installation targeting Dome
  tutorials/02_installation.md
Labels: documentation

#117 Enable actions CI for forks (v3)
  .github/workflows/ci.yml
Labels: 🔮 dome

#118 Enable actions CI for forks
  .github/workflows/ci.yml
Labels: 🏰 citadel

#105 Tutorial switching physics engines
  tutorials.md.in
  tutorials/04-switching-physics-engines.md
Labels: documentation

#104 Tutorial introduction to Ignition Physics
  tutorials/01_intro.md
Labels: documentation

#127 Fix getting model bounding box in world frame in TPE
  tpe/plugin/src/KinematicsFeatures.cc
  tpe/plugin/src/SimulationFeatures_TEST.cc
Labels: 🏰 citadel

#130 Improve fork experience
  .github/workflows/ci.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
Labels: 🏰 citadel

#129 2 ➡️ 3
  .github/workflows/ci.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  CMakeLists.txt
  Changelog.md
  dartsim/src/SDFFeatures.cc
  dartsim/src/ShapeFeatures.cc
  dartsim/src/ShapeFeatures.hh
  dartsim/src/ShapeFeatures_TEST.cc
  dartsim/worlds/slip_compliance.sdf
  include/ignition/physics/Shape.hh
  include/ignition/physics/detail/Shape.hh
  sdf/include/ignition/physics/sdf/ConstructModel.hh
  sdf/include/ignition/physics/sdf/ConstructNestedModel.hh
  tpe/lib/src/Model.cc
  tpe/lib/src/Model.hh
  tpe/lib/src/Model_TEST.cc
  tpe/plugin/src/Base.hh
  tpe/plugin/src/FreeGroupFeatures.cc
  tpe/plugin/src/KinematicsFeatures.cc
  tpe/plugin/src/SDFFeatures.cc
  tpe/plugin/src/SDFFeatures.hh
  tpe/plugin/src/SDFFeatures_TEST.cc
  tpe/plugin/src/SimulationFeatures_TEST.cc
  tpe/plugin/worlds/nested_model.world
Labels: 🔮 dome

#132 ⬆️ 3.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🔮 dome

#137 Ignore invalid joint commands
  dartsim/src/JointFeatures.cc
  dartsim/src/JointFeatures_TEST.cc
Labels: 📜 blueprint

#115 Tutorial loading physics plugin
  tutorials.md.in
  tutorials/05_plugin_loading.md
Labels: documentation

#128 Tutorial implement a physics plugin
  tutorials.md.in
  tutorials/07-implementing-a-physics-plugin.md
Labels: documentation

#147 Merge ign-physics1 -> ign-physics2
  dartsim/src/JointFeatures.cc
  dartsim/src/JointFeatures_TEST.cc
Labels: 🏰 citadel

#149 Merge ign-physics2 -> ign-physics3
  dartsim/src/JointFeatures.cc
  dartsim/src/JointFeatures_TEST.cc
Labels: 🏢 edifice, 🔮 dome

#131 Tutorial implement a custom feature
  tutorials.md.in
  tutorials/08-implementing-a-custom-feature.md
Labels: documentation

#133 Compile examples in CI
  test/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/integration/ExamplesBuild_TEST.cc
  test/integration/test_config.h.in
  test/integration/win_dirent.h
Labels: tests
