Repository gazebosim/gz-physics, pull requests merged in 2020-11, with the labels that each got.

#148 dartsim-plugin windows build fixes
  dartsim/CMakeLists.txt
  test/plugins/CMakeLists.txt
  tools/check_test_ran.py
  tpe/plugin/CMakeLists.txt
Labels: DART, Windows, 🏢 edifice, 🔮 dome

#154 Resolve updated codecheck issues
  dartsim/src/CustomMeshShape.cc
  dartsim/src/EntityManagementFeatures.cc
  dartsim/src/SDFFeatures.cc
  dartsim/src/ShapeFeatures.cc
  include/ignition/physics/Cloneable.hh
  include/ignition/physics/RelativeQuantity.hh
Labels: 📜 blueprint

#155 Preparing for 1.10 release
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#144 Advanced tutorial: Implement physics engine as a plugin
  tutorials.md.in
  tutorials/09-set-up-physics-engine-tpe.md
Labels: documentation

#158 1 to 2
  Changelog.md
  dartsim/src/CustomMeshShape.cc
  dartsim/src/EntityManagementFeatures.cc
  dartsim/src/SDFFeatures.cc
  dartsim/src/ShapeFeatures.cc
  include/ignition/physics/Cloneable.hh
  include/ignition/physics/RelativeQuantity.hh
Labels: 🏰 citadel

#142 Support setting canonical link
  tpe/lib/src/Model.cc
  tpe/lib/src/Model.hh
  tpe/lib/src/Model_TEST.cc
  tpe/plugin/src/FreeGroupFeatures.cc
  tpe/plugin/src/SDFFeatures.cc
  tpe/plugin/src/SDFFeatures_TEST.cc
Labels: TPE, 🏰 citadel

#159 2 to 3
  Changelog.md
  dartsim/src/CustomMeshShape.cc
  dartsim/src/EntityManagementFeatures.cc
  dartsim/src/SDFFeatures.cc
  dartsim/src/ShapeFeatures.cc
  include/ignition/physics/Cloneable.hh
  include/ignition/physics/RelativeQuantity.hh
Labels: 🏢 edifice, 🔮 dome
