Repository gazebosim/gz-physics, pull requests merged in 2020-12, with the labels that each got.

#165 API documentation common Set* features
  include/ignition/physics/CylinderShape.hh
  include/ignition/physics/FreeGroup.hh
  include/ignition/physics/Joint.hh
  include/ignition/physics/RemoveEntities.hh
  include/ignition/physics/Shape.hh
Labels: documentation

#120 Tutorials physics simulation terminology
  tutorials.md.in
  tutorials/06-physics-simulation-concepts.md
Labels: documentation

#173 [Bullet] Collision Features
  bullet/src/Base.hh
  bullet/src/EntityManagementFeatures.cc
  bullet/src/SDFFeatures.cc
  bullet/src/SDFFeatures.hh
  bullet/src/SimulationFeatures.hh
Labels: 🏢 edifice, 🔮 dome

#162 API documentation common Get* feature
  include/ignition/physics/GetBoundingBox.hh
  include/ignition/physics/GetEntities.hh
  include/ignition/physics/Joint.hh
  include/ignition/physics/Shape.hh
Labels: documentation

#163 API documentation common Attach* features
  include/ignition/physics/BoxShape.hh
  include/ignition/physics/CylinderShape.hh
  include/ignition/physics/PlaneShape.hh
  include/ignition/physics/SphereShape.hh
Labels: documentation

#164 API documentation common Construct* features
  include/ignition/physics/ConstructEmpty.hh
Labels: documentation

#182 Fix TPE poseDirty getter
  dartsim/src/EntityManagementFeatures.cc
  tpe/lib/src/Entity.cc
Labels: 🏰 citadel
