Repository gazebosim/gz-physics, pull requests merged in 2021-07, with the labels that each got.

#218 Heightmaps 🏔️
  CMakeLists.txt
  dartsim/CMakeLists.txt
  dartsim/src/CustomHeightmapShape.cc
  dartsim/src/CustomHeightmapShape.hh
  dartsim/src/EntityManagement_TEST.cc
  dartsim/src/SDFFeatures.cc
  dartsim/src/ShapeFeatures.cc
  dartsim/src/ShapeFeatures.hh
  heightmap/CMakeLists.txt
  heightmap/include/ignition/physics/heightmap/HeightmapShape.hh
  heightmap/include/ignition/physics/heightmap/detail/HeightmapShape.hh
  resources/heightmap_bowl.png
  tutorials/03_physics_plugins.md
  tutorials/08-implementing-a-custom-feature.md
Labels: DART, enhancement, 🏢 edifice

#261 Clean up functions that trigger GCC9 warnings
  tpe/lib/src/AABBTree.cc
  tpe/lib/src/Collision.hh
  tpe/lib/src/CollisionDetector.cc
  tpe/lib/src/Entity.hh
  tpe/lib/src/Link.hh
  tpe/lib/src/Model.hh
  tpe/lib/src/Shape.cc
  tpe/lib/src/Shape.hh
Labels: 🏯 fortress

#270 🎈 3.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#277 🎈 4.2.0~pre1 Prerelease
  CMakeLists.txt
  Changelog.md
  Migration.md
Labels: 🏢 edifice

#275 Add Gravity Feature, fix LinkFeatures_TEST
  dartsim/src/LinkFeatures_TEST.cc
  dartsim/src/ShapeFeatures_TEST.cc
  dartsim/src/WorldFeatures.cc
  dartsim/src/WorldFeatures.hh
  dartsim/src/WorldFeatures_TEST.cc
  include/ignition/physics/World.hh
  include/ignition/physics/detail/FrameSemantics.hh
  include/ignition/physics/detail/World.hh
Labels: 🏢 edifice

#279 🎈 4.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#276 Remove use of deprecated function sdf::JointAxis::InitialPosition
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures_TEST.cc
  dartsim/worlds/test.world
Labels: needs upstream release, 🏯 fortress

#280 Remove outdated comment
  dartsim/src/SDFFeatures.cc
Labels: 🏯 fortress

#260 Added DART feature for setting joint limits dynamically.
  dartsim/src/JointFeatures.cc
  dartsim/src/JointFeatures.hh
  dartsim/src/JointFeatures_TEST.cc
  dartsim/src/SDFFeatures_TEST.cc
  dartsim/worlds/test.world
  include/ignition/physics/Joint.hh
  include/ignition/physics/detail/Joint.hh
Labels: DART, needs upstream release, 🔮 dome
