Repository gazebosim/gz-physics, pull requests merged in 2021-06, with the labels that each got.

#263 Fix dart deprecation warning
  test/plugins/DARTDoublePendulum.cc
Labels: 🏰 citadel

#266 🎈 3.3.0~pre1
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#265 Use slip compliance API's available in upstream dartsim release
  dartsim/src/SDFFeatures.cc
  dartsim/src/ShapeFeatures.cc
  dartsim/src/ShapeFeatures_TEST.cc
Labels: 🏰 citadel

#269 2 ➡️ 3
  dartsim/src/SDFFeatures.cc
  dartsim/src/ShapeFeatures.cc
  dartsim/src/ShapeFeatures_TEST.cc
Labels: 🔮 dome

#268 [dartsim] Fix collision detection issue when using joints across nested models
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures_TEST.cc
  dartsim/worlds/joint_across_nested_models.sdf
Labels: 🏢 edifice

#203 Added Ellipsoid and Capsule shapes to TPE
  tpe/lib/src/Collision.cc
  tpe/lib/src/CollisionDetector_TEST.cc
  tpe/lib/src/Collision_TEST.cc
  tpe/lib/src/Shape.cc
  tpe/lib/src/Shape.hh
  tpe/lib/src/Shape_TEST.cc
  tpe/plugin/src/SDFFeatures.cc
  tpe/plugin/src/ShapeFeatures.cc
  tpe/plugin/src/ShapeFeatures.hh
  tpe/plugin/src/SimulationFeatures_TEST.cc
  tpe/plugin/worlds/shapes.world
Labels: TPE, 🏢 edifice
