Repository gazebosim/gz-physics, pull requests merged in 2021-09, with the labels that each got.

#288 [dartsim] Add support for joint frame semantics
  dartsim/src/Base.hh
  dartsim/src/KinematicsFeatures.cc
  dartsim/src/KinematicsFeatures.hh
  dartsim/src/KinematicsFeatures_TEST.cc
  dartsim/worlds/string_pendulum.sdf
Labels: 🏰 citadel

#290 2 ➡️ 3
  .github/CODEOWNERS
  bitbucket-pipelines.yml
  dartsim/src/Base.hh
  dartsim/src/KinematicsFeatures.cc
  dartsim/src/KinematicsFeatures.hh
  dartsim/src/KinematicsFeatures_TEST.cc
  dartsim/worlds/string_pendulum.sdf
Labels: 🔮 dome, beta

#291 3 ➡️ 4
  .github/CODEOWNERS
  CMakeLists.txt
  Changelog.md
  bitbucket-pipelines.yml
  dartsim/src/Base.hh
  dartsim/src/JointFeatures.cc
  dartsim/src/JointFeatures.hh
  dartsim/src/JointFeatures_TEST.cc
  dartsim/src/KinematicsFeatures.cc
  dartsim/src/KinematicsFeatures.hh
  dartsim/src/KinematicsFeatures_TEST.cc
  dartsim/src/SDFFeatures_TEST.cc
  dartsim/worlds/string_pendulum.sdf
  dartsim/worlds/test.world
  include/ignition/physics/Joint.hh
  include/ignition/physics/detail/Joint.hh
Labels: beta, 🏢 edifice

#292 4 ➡️ 5 (main)
  .github/CODEOWNERS
  CMakeLists.txt
  Changelog.md
  bitbucket-pipelines.yml
  dartsim/src/Base.hh
  dartsim/src/JointFeatures.cc
  dartsim/src/JointFeatures.hh
  dartsim/src/JointFeatures_TEST.cc
  dartsim/src/KinematicsFeatures.cc
  dartsim/src/KinematicsFeatures.hh
  dartsim/src/KinematicsFeatures_TEST.cc
  dartsim/src/SDFFeatures_TEST.cc
  dartsim/worlds/string_pendulum.sdf
  dartsim/worlds/test.world
  include/ignition/physics/Joint.hh
  include/ignition/physics/detail/Joint.hh
  src/CMakeLists.txt
  tpe/plugin/src/KinematicsFeatures.cc
  tpe/plugin/src/SimulationFeatures.cc
  tpe/plugin/src/SimulationFeatures.hh
  tpe/plugin/src/SimulationFeatures_TEST.cc
Labels: 🏯 fortress
