Repository gazebosim/gz-physics, pull requests merged in 2021-02, with the labels that each got.

#210 Added issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
Labels: 🔮 dome

#211 remove tpe codeowner
  .github/CODEOWNERS
Labels: 🏰 citadel

#213 Depend on ignition-utils1 cli component
  .github/ci/packages.apt
  CMakeLists.txt
  Migration.md
  include/ignition/physics/CompositeData.hh
  include/ignition/physics/FrameID.hh
  include/ignition/physics/detail/CompositeData.hh
  include/ignition/physics/detail/Identity.hh
  src/CMakeLists.txt
  tpe/lib/src/AABBTree.hh
  tpe/lib/src/CollisionDetector.hh
  tpe/lib/src/Engine.hh
  tpe/lib/src/Model.hh
  tpe/lib/src/Shape.hh
  tpe/lib/src/World.hh
Labels: 🏢 edifice

#189 Constructing nested models for dartsim
  dartsim/src/Base.hh
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures.hh
  dartsim/src/SDFFeatures_TEST.cc
  dartsim/worlds/world_with_nested_model.sdf
  dartsim/worlds/world_with_nested_model_joint_to_world.sdf
Labels: 🏢 edifice

#212 2 ➡️ 3
  .github/CODEOWNERS
  README.md
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures_TEST.cc
  dartsim/worlds/test.world
  include/ignition/physics/CylinderShape.hh
  include/ignition/physics/Entity.hh
  include/ignition/physics/FreeGroup.hh
  include/ignition/physics/Joint.hh
  include/ignition/physics/RemoveEntities.hh
  include/ignition/physics/Shape.hh
  tpe/lib/src/CollisionDetector.cc
  tpe/lib/src/CollisionDetector_TEST.cc
  tpe/lib/src/Entity.cc
  tpe/lib/src/Entity.hh
  tpe/lib/src/Model.cc
  tpe/lib/src/Model.hh
  tpe/lib/src/Model_TEST.cc
  tpe/plugin/src/FreeGroupFeatures.cc
  tpe/plugin/src/SDFFeatures.cc
  tpe/plugin/src/SDFFeatures_TEST.cc
  tutorials/02_installation.md
  tutorials/05_plugin_loading.md
  tutorials/06-physics-simulation-concepts.md
  tutorials/07-implementing-a-physics-plugin.md
  tutorials/08-implementing-a-custom-feature.md
Labels: 🔮 dome

#214 3 ➡️ 4
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
  README.md
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures_TEST.cc
  dartsim/worlds/test.world
  include/ignition/physics/Entity.hh
  tpe/lib/src/CollisionDetector.cc
  tpe/lib/src/CollisionDetector_TEST.cc
  tpe/lib/src/Entity.cc
  tpe/lib/src/Entity.hh
  tpe/lib/src/Model.cc
  tpe/lib/src/Model.hh
  tpe/lib/src/Model_TEST.cc
  tpe/plugin/src/FreeGroupFeatures.cc
  tpe/plugin/src/SDFFeatures.cc
  tpe/plugin/src/SDFFeatures_TEST.cc
  tutorials/02_installation.md
  tutorials/05_plugin_loading.md
  tutorials/06-physics-simulation-concepts.md
  tutorials/07-implementing-a-physics-plugin.md
  tutorials/08-implementing-a-custom-feature.md
  tutorials/09-set-up-physics-engine-tpe.md
Labels: 🏢 edifice

#215 Removed issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
Labels: 🔮 dome

#205 Bump in edifice: ign-common4
  .github/ci/packages.apt
  CMakeLists.txt
  bitbucket-pipelines.yml
Labels: needs upstream release, 🏢 edifice
