Repository gazebosim/gz-physics, pull requests merged in 2021-11, with the labels that each got.

#305 Remove unused ign_auto_headers.hh.in
  include/ignition/physics/ign_auto_headers.hh.in
Labels: 🏰 citadel

#306 Prepare for 2.5.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#307 2 ➡️ 3
  Changelog.md
  dartsim/CMakeLists.txt
  dartsim/src/SimulationFeatures.cc
  dartsim/src/SimulationFeatures.hh
  dartsim/src/SimulationFeatures_TEST.cc
  include/ignition/physics/ContactProperties.hh
  include/ignition/physics/detail/ContactProperties.hh
  include/ignition/physics/ign_auto_headers.hh.in
  tpe/plugin/src/SimulationFeatures_TEST.cc
Labels: 🔮 dome

#308 3 ➡️ 4
  Changelog.md
  dartsim/CMakeLists.txt
  dartsim/src/SimulationFeatures.cc
  dartsim/src/SimulationFeatures.hh
  dartsim/src/SimulationFeatures_TEST.cc
  include/ignition/physics/ContactProperties.hh
  include/ignition/physics/detail/ContactProperties.hh
  include/ignition/physics/ign_auto_headers.hh.in
  tpe/plugin/src/SimulationFeatures_TEST.cc
Labels: 🏢 edifice

#310 4 ➡️ 5
  Changelog.md
  dartsim/CMakeLists.txt
  dartsim/src/SimulationFeatures.cc
  dartsim/src/SimulationFeatures.hh
  dartsim/src/SimulationFeatures_TEST.cc
  dartsim/src/WorldFeatures_TEST.cc
  include/ignition/physics/ContactProperties.hh
  include/ignition/physics/detail/ContactProperties.hh
  include/ignition/physics/ign_auto_headers.hh.in
  tpe/plugin/src/SimulationFeatures_TEST.cc
Labels: 🏯 fortress, 🌱 garden

#311 🎈 3.4.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#313 🎈 5.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress, 🌱 garden
