Repository gazebosim/gz-physics, pull requests merged in 2021-12, with the labels that each got.

#314 Link to sdformat10 cmake target
  CMakeLists.txt
  sdf/CMakeLists.txt
Labels: 🔮 dome

#312 Fix tutorials broken ref links, snippets, image widths
  dartsim/include/ignition/physics/dartsim/World.hh
  dartsim/src/CustomFeatures.cc
  dartsim/src/CustomFeatures.hh
  tutorials/05_plugin_loading.md
  tutorials/06-physics-simulation-concepts.md
  tutorials/07-implementing-a-physics-plugin.md
  tutorials/08-implementing-a-custom-feature.md
Labels: documentation

#317 Prepare for 3.4.1 release
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#316 Fix tutorial snippets with new Doxygen filters
  tutorials/05_plugin_loading.md
  tutorials/07-implementing-a-physics-plugin.md
  tutorials/08-implementing-a-custom-feature.md
Labels: documentation

#321 5 ➡️ 6 (main)
  Changelog.md
  bullet/CMakeLists.txt
  dartsim/CMakeLists.txt
  dartsim/src/SimulationFeatures.cc
  dartsim/src/SimulationFeatures.hh
  dartsim/src/SimulationFeatures_TEST.cc
  dartsim/src/WorldFeatures_TEST.cc
  include/ignition/physics/ContactProperties.hh
  include/ignition/physics/detail/ContactProperties.hh
  include/ignition/physics/ign_auto_headers.hh.in
  tpe/plugin/src/SimulationFeatures_TEST.cc
Labels: 🌱 garden
