Repository gazebosim/gz-physics, pull requests merged in 2021-04, with the labels that each got.

#179 [TPE] Update link pose
  tpe/lib/src/Entity.hh
  tpe/lib/src/Link.cc
  tpe/lib/src/Link.hh
  tpe/lib/src/Link_TEST.cc
  tpe/lib/src/Model.cc
  tpe/lib/src/Model.hh
  tpe/lib/src/Model_TEST.cc
  tpe/lib/src/World.cc
  tpe/plugin/src/FreeGroupFeatures.cc
  tpe/plugin/src/SDFFeatures.cc
Labels: 🏰 citadel

#247 🎈 2.4.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#251 2 ➡️ 3
  Changelog.md
  tpe/lib/src/Entity.hh
  tpe/lib/src/Link.cc
  tpe/lib/src/Link.hh
  tpe/lib/src/Link_TEST.cc
  tpe/lib/src/Model.cc
  tpe/lib/src/Model.hh
  tpe/lib/src/Model_TEST.cc
  tpe/lib/src/World.cc
  tpe/plugin/src/FreeGroupFeatures.cc
  tpe/plugin/src/SDFFeatures.cc
Labels: 🔮 dome

#252 🎈 3.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#253 3 ➡️ 4
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
  CMakeLists.txt
  Changelog.md
  README.md
  tpe/lib/src/Entity.hh
  tpe/lib/src/Link.cc
  tpe/lib/src/Link.hh
  tpe/lib/src/Link_TEST.cc
  tpe/lib/src/Model.cc
  tpe/lib/src/Model.hh
  tpe/lib/src/Model_TEST.cc
  tpe/lib/src/World.cc
  tpe/plugin/src/FreeGroupFeatures.cc
  tpe/plugin/src/SDFFeatures.cc
  tutorials/02_installation.md
  tutorials/03_physics_plugins.md
  tutorials/06-physics-simulation-concepts.md
  tutorials/08-implementing-a-custom-feature.md
Labels: 🏢 edifice
