Repository gazebosim/gz-physics, pull requests merged in 2021-08, with the labels that each got.

#281 Add azeey and scpeters as code owners
  .github/CODEOWNERS
Labels: 🏰 citadel

#282 Make ignition-physics CMake config files relocatable
  src/CMakeLists.txt
Labels: 🏢 edifice

#287 👩‍🌾 Remove bitbucket-pipelines.yml
  bitbucket-pipelines.yml
Labels: 🏰 citadel

#289 Fix TPE Link velocity not being updated and Model velocity not having any effect.
  tpe/plugin/src/KinematicsFeatures.cc
  tpe/plugin/src/SimulationFeatures.cc
  tpe/plugin/src/SimulationFeatures.hh
  tpe/plugin/src/SimulationFeatures_TEST.cc
Labels: bug, TPE, 🏢 edifice
