Repository gazebosim/gz-physics, pull requests merged in 2021-01, with the labels that each got.

#185 Fix compilation with GCC 10.2.0
  include/ignition/physics/Entity.hh
Labels: 🏰 citadel

#139 Add restitution coefficient support for bouncing
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures_TEST.cc
  dartsim/worlds/test.world
Labels: 🏰 citadel

#190 [bullet] Joints implementation
  bullet/src/Base.hh
  bullet/src/JointFeatures.cc
  bullet/src/JointFeatures.hh
  bullet/src/KinematicsFeatures.cc
  bullet/src/SDFFeatures.cc
  bullet/src/SDFFeatures.hh
  bullet/src/ShapeFeatures.cc
  bullet/src/plugin.cc
Labels: Bullet

#181 TPE: Skip computing collisions for static objects
  tpe/lib/src/CollisionDetector.cc
  tpe/lib/src/CollisionDetector_TEST.cc
  tpe/lib/src/Entity.cc
  tpe/lib/src/Entity.hh
  tpe/lib/src/Model_TEST.cc
  tpe/plugin/src/SDFFeatures.cc
Labels: TPE, 🏰 citadel

#192 [Bullet] Parameter tuning
  bullet/src/Base.hh
  bullet/src/JointFeatures.cc
  bullet/src/SDFFeatures.cc
  bullet/src/SimulationFeatures.cc
Labels: 🔮 dome

#197 [bullet] Getters for revolute joints
  bullet/src/JointFeatures.cc
  bullet/src/SDFFeatures.cc
Labels: Bullet, 🔮 dome

#194 Add Windows installation
  README.md
  tutorials/02_installation.md
Labels: 🏰 citadel

#187 Tutorials and API doc back port
  include/ignition/physics/BoxShape.hh
  include/ignition/physics/ConstructEmpty.hh
  include/ignition/physics/CylinderShape.hh
  include/ignition/physics/FreeGroup.hh
  include/ignition/physics/GetBoundingBox.hh
  include/ignition/physics/GetEntities.hh
  include/ignition/physics/Joint.hh
  include/ignition/physics/PlaneShape.hh
  include/ignition/physics/RemoveEntities.hh
  include/ignition/physics/Shape.hh
  include/ignition/physics/SphereShape.hh
  tutorials.md.in
  tutorials/01_intro.md
  tutorials/02_installation.md
  tutorials/05_plugin_loading.md
  tutorials/06-physics-simulation-concepts.md
  tutorials/07-implementing-a-physics-plugin.md
  tutorials/08-implementing-a-custom-feature.md
Labels: documentation, 🏰 citadel

#201 fix cpplint error
  dartsim/src/EntityManagementFeatures.cc
Labels: 🔮 dome

#206 [Bullet] Adds missing getters/setters revolute joints
  bullet/src/JointFeatures.cc
  bullet/src/SDFFeatures.cc
Labels: Bullet
