Repository gazebosim/gz-physics, pull requests merged in 2021-05, with the labels that each got.

#255 🎈 4.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#256 Port codecov to new configuration
  .github/workflows/ci.yml
Labels: 🏯 fortress

#257 Remove tools/code_check and update codecov
  .github/workflows/ci.yml
  CMakeLists.txt
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cpplint.py
Labels: 🏰 citadel

#208 Integrate bullet into ign-physics3
  CMakeLists.txt
  bullet/CMakeLists.txt
  bullet/src/Base.hh
  bullet/src/EntityManagementFeatures.cc
  bullet/src/EntityManagementFeatures.hh
  bullet/src/EntityManagement_TEST.cc
  bullet/src/FreeGroupFeatures.cc
  bullet/src/FreeGroupFeatures.hh
  bullet/src/JointFeatures.cc
  bullet/src/JointFeatures.hh
  bullet/src/KinematicsFeatures.cc
  bullet/src/KinematicsFeatures.hh
  bullet/src/SDFFeatures.cc
  bullet/src/SDFFeatures.hh
  bullet/src/SDFFeatures_TEST.cc
  bullet/src/ShapeFeatures.cc
  bullet/src/ShapeFeatures.hh
  bullet/src/SimulationFeatures.cc
  bullet/src/SimulationFeatures.hh
  bullet/src/plugin.cc
Labels: Bullet, 🔮 dome
