Repository gazebosim/gz-physics, pull requests merged in 2021-03, with the labels that each got.

#217 ign-utils -> ign-utils1
  .github/ci/packages.apt
Labels: needs upstream release, 🏢 edifice

#221 Master branch updates
  .github/workflows/ci.yml
  README.md
  tutorials/03_physics_plugins.md
  tutorials/06-physics-simulation-concepts.md
  tutorials/08-implementing-a-custom-feature.md
Labels: 🏰 citadel

#232 2 to 3
  .github/workflows/ci.yml
  README.md
  tutorials/02_installation.md
  tutorials/03_physics_plugins.md
  tutorials/06-physics-simulation-concepts.md
  tutorials/08-implementing-a-custom-feature.md
  tutorials/09-set-up-physics-engine-tpe.md
Labels: 🔮 dome

#235 3 ➡️ 4
  .github/workflows/ci.yml
  README.md
  test/integration/ExamplesBuild_TEST.cc
  tutorials/02_installation.md
  tutorials/03_physics_plugins.md
  tutorials/05_plugin_loading.md
  tutorials/06-physics-simulation-concepts.md
  tutorials/07-implementing-a-physics-plugin.md
  tutorials/08-implementing-a-custom-feature.md
  tutorials/09-set-up-physics-engine-tpe.md
Labels: beta, 🏢 edifice

#220 [dartsim] Fix joint construction errors due to link name duplication or BodyNodes moving to other skeletons
  dartsim/src/Base.hh
  dartsim/src/Base_TEST.cc
  dartsim/src/EntityManagementFeatures.cc
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures.hh
  dartsim/src/SDFFeatures_TEST.cc
  dartsim/worlds/world_with_nested_model.sdf
Labels: beta, 🏢 edifice

#227 [dartsim] Ensure Link and Model APIs continue to work after joint creation in DART
  dartsim/src/Base.hh
  dartsim/src/Base_TEST.cc
  dartsim/src/EntityManagementFeatures.cc
  dartsim/src/EntityManagement_TEST.cc
  dartsim/src/JointFeatures_TEST.cc
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures_TEST.cc
Labels: DART, beta, enhancement, 🏢 edifice

#223 write modified link data to output in physics step
  dartsim/src/SimulationFeatures.cc
  dartsim/src/SimulationFeatures.hh
  dartsim/src/SimulationFeatures_TEST.cc
  include/ignition/physics/CanWriteData.hh
  tpe/plugin/src/SimulationFeatures.cc
  tpe/plugin/src/SimulationFeatures.hh
  tpe/plugin/src/SimulationFeatures_TEST.cc
Labels: beta, enhancement, performance, 🏢 edifice

#234 Rename CanonicalLink to RootLink
  Migration.md
  dartsim/src/FreeGroupFeatures.cc
  dartsim/src/FreeGroupFeatures.hh
  include/ignition/physics/FreeGroup.hh
  include/ignition/physics/detail/FreeGroup.hh
  tpe/plugin/src/FreeGroupFeatures.cc
  tpe/plugin/src/FreeGroupFeatures.hh
  tpe/plugin/src/SimulationFeatures_TEST.cc
Labels: beta, 🏢 edifice

#228 [dartsim] Add empty nested model construction and nested model entity management
  dartsim/src/Base.hh
  dartsim/src/Base_TEST.cc
  dartsim/src/EntityManagementFeatures.cc
  dartsim/src/EntityManagementFeatures.hh
  dartsim/src/EntityManagement_TEST.cc
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures_TEST.cc
  include/ignition/physics/ConstructEmpty.hh
  include/ignition/physics/GetEntities.hh
  include/ignition/physics/detail/ConstructEmpty.hh
  include/ignition/physics/detail/GetEntities.hh
Labels: DART, beta, enhancement, 🏢 edifice

#238 Add "ChangedWorldPose" to ForwardStep::Output's expected data
  dartsim/src/SimulationFeatures.cc
  dartsim/src/SimulationFeatures.hh
  dartsim/src/SimulationFeatures_TEST.cc
  include/ignition/physics/ForwardStep.hh
  tpe/plugin/src/SimulationFeatures.cc
  tpe/plugin/src/SimulationFeatures.hh
  tpe/plugin/src/SimulationFeatures_TEST.cc
Labels: 🏢 edifice

#202 Added ellipsoid and capsule to dartsim
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures_TEST.cc
  dartsim/src/ShapeFeatures.cc
  dartsim/src/ShapeFeatures.hh
  dartsim/worlds/shapes.sdf
  include/ignition/physics/CapsuleShape.hh
  include/ignition/physics/EllipsoidShape.hh
  include/ignition/physics/detail/CapsuleShape.hh
  include/ignition/physics/detail/EllipsoidShape.hh
  test/performance/symbol_names.cc
  tpe/plugin/src/SDFFeatures.cc
Labels: DART, beta, 🏢 edifice

#225 Set collision detector and solver for DART
  CMakeLists.txt
  dartsim/src/WorldFeatures.cc
  dartsim/src/WorldFeatures.hh
  dartsim/src/WorldFeatures_TEST.cc
  dartsim/src/plugin.cc
  include/ignition/physics/World.hh
  include/ignition/physics/detail/World.hh
  tpe/lib/src/CollisionDetector_TEST.cc
  tutorials/03_physics_plugins.md
Labels: DART, beta, close the gap, enhancement, 🏢 edifice

#224 dartsim: fdir1 expressed_in frame from SDFormat
  dartsim/src/SDFFeatures.cc
Labels: DART, beta, enhancement, 🏢 edifice

#229 [tpe] Add empty nested model construction and nested model entity management
  tpe/lib/src/Model.cc
  tpe/lib/src/Model.hh
  tpe/plugin/src/Base.hh
  tpe/plugin/src/Base_TEST.cc
  tpe/plugin/src/EntityManagementFeatures.cc
  tpe/plugin/src/EntityManagementFeatures.hh
  tpe/plugin/src/EntityManagement_TEST.cc
Labels: TPE, beta, enhancement, 🏢 edifice

#239 Add dart-bullet dependency to CI
  .github/ci/packages-bionic.apt
  .github/ci/packages-focal.apt
Labels: beta, bug, 🏢 edifice

#230 Remove nested models
  dartsim/src/Base.hh
  dartsim/src/EntityManagementFeatures.cc
  dartsim/src/EntityManagementFeatures.hh
  dartsim/src/EntityManagement_TEST.cc
  dartsim/src/JointFeatures.cc
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures_TEST.cc
  include/ignition/physics/RemoveEntities.hh
  include/ignition/physics/detail/RemoveEntities.hh
  tpe/lib/src/Model.cc
  tpe/lib/src/Model.hh
  tpe/plugin/src/Base.hh
  tpe/plugin/src/EntityManagementFeatures.cc
  tpe/plugin/src/EntityManagementFeatures.hh
  tpe/plugin/src/EntityManagement_TEST.cc
Labels: DART, TPE, beta, enhancement, 🏢 edifice

#240 [Bullet] Auxiliar PR to add index to identity conversion
  bullet/src/Base.hh
  bullet/src/EntityManagementFeatures.cc
  bullet/src/SDFFeatures.cc
  bullet/src/ShapeFeatures.cc
Labels: Bullet

#241 🎈 4.0.0~pre1
  Changelog.md
Labels: beta, 🏢 edifice

#243 🥳 Tweaks to README: TPE, shapes, version...
  README.md
Labels: documentation, 🏢 edifice

#242 Improved Windows instructions
  examples/hello_world_loader/README.md
  examples/hello_world_plugin/README.md
Labels: Windows, documentation, 🏢 edifice
