Repository gazebosim/gz-physics, pull requests merged in 2022-03, with the labels that each got.

#328 Remove explicitly-defined copy constructor/operator
  tpe/lib/src/Shape.cc
  tpe/lib/src/Shape.hh
Labels: 🌱 garden

#329 Add Ubuntu Jammy CI
  .github/ci/packages-jammy.apt
  .github/workflows/ci.yml
Labels: 🏯 fortress

#331 Remove Bionic from future releases (Garden+)
  .github/ci/packages-bionic.apt
  .github/workflows/ci.yml
  README.md
  tutorials/02_installation.md
Labels: 🌱 garden

#315 Added DEM support to heightmaps
  CMakeLists.txt
  dartsim/CMakeLists.txt
  dartsim/src/CustomHeightmapShape.cc
  dartsim/src/CustomHeightmapShape.hh
  dartsim/src/EntityManagement_TEST.cc
  heightmap/CMakeLists.txt
  heightmap/include/ignition/physics/heightmap/HeightmapShape.hh
  resources/volcano.tif
Labels: DART, needs upstream release, 🌱 garden

#336 Merge 5 -> main
  .github/ci/packages-jammy.apt
  .github/workflows/ci.yml
  Changelog.md
  dartsim/src/JointFeatures_TEST.cc
  dartsim/src/KinematicsFeatures_TEST.cc
  dartsim/src/LinkFeatures_TEST.cc
  dartsim/src/ShapeFeatures_TEST.cc
  dartsim/src/WorldFeatures_TEST.cc
  examples/hello_world_loader/CMakeLists.txt
  examples/hello_world_plugin/CMakeLists.txt
  examples/simple_plugin/CMakeLists.txt
Labels: 🌱 garden

#335 Fix ExpectData compiler warnings
  include/ignition/physics/SpecifyData.hh
Labels: 🌱 garden
