Repository gazebosim/gz-physics, pull requests merged in 2022-10, with the labels that each got.

#433 Bullet-featherstone: Refactor joint code
  bullet-featherstone/src/SDFFeatures.cc
Labels: Bullet

#436 Fix bullet cmake, probably bad merge
  bullet/CMakeLists.txt
Labels: 🌱 garden

#437 Backport windows fix
  bullet/CMakeLists.txt
Labels: 🏯 fortress

#443 Add top-level bullet-featherstone README
  README.md
  bullet-featherstone/README.md
Labels: 🌱 garden

#444 Removed GetCollision API it's redundant
  bullet-featherstone/src/SDFFeatures.cc
  bullet-featherstone/src/SDFFeatures.hh
  bullet/src/SDFFeatures.cc
  bullet/src/SDFFeatures.hh
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures.hh
  sdf/include/gz/physics/sdf/ConstructCollision.hh
  tpe/plugin/src/SDFFeatures.cc
  tpe/plugin/src/SDFFeatures.hh
Labels: 🌱 garden

#441 🎈 6.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#445 Fix construction of nested models
  dartsim/src/SDFFeatures.cc
Labels: 🌱 garden
