Repository gazebosim/gz-physics, pull requests merged in 2022-08, with the labels that each got.

#351 dartsim: fix handling inertia matrix pose rotation
  dartsim/src/SDFFeatures.cc
Labels: bug, DART, 🏯 fortress

#398 Merge ign-physics5 ➡️ main
  coverage.ignore.in
  dartsim/src/SDFFeatures.cc
Labels: 🌱 garden

#400 ign -> gz : Remove redundant namespace references
  dartsim/src/JointFeatures_TEST.cc
  dartsim/src/KinematicsFeatures_TEST.cc
  dartsim/src/LinkFeatures_TEST.cc
  dartsim/src/ShapeFeatures_TEST.cc
  src/FeatureList_TEST.cc
  test/integration/DoublePendulum.cc
  test/integration/FeatureSystem.cc
  tpe/lib/src/CollisionDetector_TEST.cc
  tpe/lib/src/Collision_TEST.cc
  tpe/plugin/src/ShapeFeatures.cc
Labels: 🏰 citadel, ign to gz

#403 🎈 2.5.1
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#401 README: update CI badges, fix expected joint limits
  README.md
  dartsim/src/SDFFeatures_TEST.cc
Labels: documentation, 🌱 garden

#406 Updated Codecov ignored files
  codecov.yml
Labels: 🌱 garden
