Repository gazebosim/gz-physics, pull requests merged in 2022-11, with the labels that each got.

#446 Suppress MSVC warning that is not applicable
  include/gz/physics/FeatureList.hh
Labels: 🌱 garden

#447 🎈 6.1.1
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#448 Deduplicate common tests part1
  test/common_test/construct_empty_world.cc
Labels: 🌱 garden

#384 Support fluid added mass
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures_TEST.cc
  dartsim/worlds/added_mass.sdf
Labels: enhancement, 🌱 garden, MBARI buoy

#452 Reduce error to debug and add notes
  dartsim/src/SDFFeatures.cc
Labels: 🌱 garden

#453 Prepare for 6.2.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#454 2.6.0~pre1
  CMakeLists.txt
Labels: 🏰 citadel

#455 2.6.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel
