Repository gazebosim/gz-physics, pull requests merged in 2022-09, with the labels that each got.

#407 Improved simulation features common tests
  bullet/CMakeLists.txt
  bullet/src/EntityManagement_TEST.cc
  bullet/src/SDFFeatures_TEST.cc
  dartsim/src/SimulationFeatures_TEST.cc
  test/common_test/simulation_features.cc
  test/common_test/worlds/contact.sdf
  test/common_test/worlds/falling.world
Labels: 🌱 garden

#415 Revert "Updated Codecov ignored files"
  codecov.yml
Labels: 🌱 garden

#404 Improved joints in bullet featherstone
  bullet-featherstone/src/SDFFeatures.cc
Labels: Bullet

#416 Updates to installation documentation
  tutorials/02_installation.md
Labels: 🌱 garden

#417 Fix broken links in the physics plugin tutorial
  tutorials/03_physics_plugins.md
Labels: 🌱 garden

#414 Added world features common tests
  dartsim/src/WorldFeatures_TEST.cc
  test/common_test/CMakeLists.txt
  test/common_test/world_features.cc
Labels: 🌱 garden

#382 Added Shapes Features to bullet-featherstone
  CMakeLists.txt
  bullet-featherstone/CMakeLists.txt
  bullet-featherstone/src/Base.cc
  bullet-featherstone/src/KinematicsFeatures.cc
  bullet-featherstone/src/SDFFeatures.cc
  bullet-featherstone/src/SDFFeatures.hh
  bullet-featherstone/src/ShapeFeatures.cc
  bullet-featherstone/src/ShapeFeatures.hh
  bullet-featherstone/src/plugin.cc
  test/common_test/simulation_features.cc
Labels: enhancement, Bullet

#422 Updated 06-physics-simulation-concepts instructions
  tutorials/06-physics-simulation-concepts.md
Labels: 🌱 garden

#421 Improved 04-switching-physics-engines instructions
  tutorials/04-switching-physics-engines.md
Labels: 🌱 garden

#419 Restructure TPE related tutorials
  examples/simple_plugin/EntityManagementFeatures.cc
  examples/simple_plugin/EntityManagementFeatures_TEST.cc
  examples/simple_plugin/plugin.cc
  tutorials.md.in
  tutorials/09-set-up-physics-engine-tpe.md
  tutorials/09_use_custom_engine.md
Labels: 🌱 garden
