Repository gazebosim/gz-physics, pull requests merged in 2022-06, with the labels that each got.

#350 Bullet: Added collision shape to Capsule and Ellipsoid
  bullet/src/SDFFeatures.cc
Labels: Bullet, 🌱 garden

#358 [ign -> gz] CMake functions
  CMakeLists.txt
  bullet/CMakeLists.txt
  dartsim/CMakeLists.txt
  heightmap/CMakeLists.txt
  include/gz/physics/CMakeLists.txt
  mesh/CMakeLists.txt
  sdf/CMakeLists.txt
  src/CMakeLists.txt
  test/benchmark/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/regression/CMakeLists.txt
  test/static_assert/CMakeLists.txt
  tpe/lib/CMakeLists.txt
  tpe/plugin/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#359 Suggestion: Added basic architecture for common tests with cmd arguments
  test/common_test/CMakeLists.txt
  test/common_test/basic_test.cc
Labels: tests, 🌱 garden

#357 Added basic architecture for common tests
  bullet/src/EntityManagementFeatures.cc
  bullet/src/EntityManagementFeatures.hh
  test/CMakeLists.txt
  test/common_test/CMakeLists.txt
  test/common_test/basic_test.cc
Labels: DART, TPE, Bullet, 🌱 garden

#355 Rename CMake project to gz
  CMakeLists.txt
  Changelog.md
  bullet/CMakeLists.txt
  dartsim/CMakeLists.txt
  dartsim/src/CustomFeatures.hh
  dartsim/worlds/falling.world
  examples/hello_world_loader/CMakeLists.txt
  examples/hello_world_loader/README.md
  examples/hello_world_plugin/CMakeLists.txt
  examples/simple_plugin/CMakeLists.txt
  heightmap/CMakeLists.txt
  include/gz/physics/FrameSemantics.hh
  include/gz/physics/Geometry.hh
  mesh/CMakeLists.txt
  src/CMakeLists.txt
  test/common_test/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/plugins/CMakeLists.txt
  tpe/lib/CMakeLists.txt
  tpe/plugin/CMakeLists.txt
  tpe/plugin/src/CustomFeatures.hh
  tutorials/04-switching-physics-engines.md
  tutorials/05_plugin_loading.md
  tutorials/06-physics-simulation-concepts.md
  tutorials/08-implementing-a-custom-feature.md
  tutorials/09-set-up-physics-engine-tpe.md
  tutorials/09_use_custom_engine.md
Labels: 🌱 garden, ign to gz

#368 ign -> gz Partial Docs Migration and Project Name Followups : gz-physics
  Changelog.md
  Migration.md
  README.md
  api.md.in
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures_TEST.cc
  examples/hello_world_loader/CMakeLists.txt
  examples/hello_world_loader/README.md
  examples/hello_world_plugin/CMakeLists.txt
  examples/hello_world_plugin/README.md
  examples/simple_plugin/CMakeLists.txt
  tpe/plugin/src/FreeGroupFeatures.cc
  tutorials.md.in
  tutorials/01_intro.md
  tutorials/02_installation.md
  tutorials/03_physics_plugins.md
  tutorials/04-switching-physics-engines.md
  tutorials/05_plugin_loading.md
  tutorials/06-physics-simulation-concepts.md
  tutorials/07-implementing-a-physics-plugin.md
  tutorials/08-implementing-a-custom-feature.md
  tutorials/09-set-up-physics-engine-tpe.md
  tutorials/09_use_custom_engine.md
Labels: 🌱 garden

#370 Fixed warning SDFfeatures_TEST - dartsim
  dartsim/src/SDFFeatures_TEST.cc
Labels: tests, 🌱 garden

#352 dartsim: support non-tree kinematics in AttachFixedJoint
  dartsim/src/Base.hh
  dartsim/src/JointFeatures.cc
  dartsim/src/JointFeatures_TEST.cc
  dartsim/src/SDFFeatures.cc
  dartsim/worlds/joint_constraint.sdf
Labels: 🏯 fortress

#371 Prepare for 5.2.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress
