Repository gazebosim/gz-physics, pull requests merged in 2022-04, with the labels that each got.

#338 2 ➡️ 5
  include/ignition/physics/SpecifyData.hh
  include/ignition/physics/detail/SpecifyData.hh
  src/SpecifyData_TEST.cc
  tpe/lib/src/Shape.cc
  tpe/lib/src/Shape.hh
Labels: 🏯 fortress

#340 examples: fix cmake find version variables
  examples/hello_world_loader/CMakeLists.txt
  examples/hello_world_plugin/CMakeLists.txt
  examples/simple_plugin/CMakeLists.txt
Labels: 🌱 garden

#339 Make CONFIG a CMake pass-through option for DART
  CMakeLists.txt
Labels: 🏰 citadel

#343 Use SuppressWarning from ign-utils
  tpe/lib/src/Link.hh
Labels: 🏯 fortress

#341 Bumps in garden : ign-physics6
  .github/ci/packages.apt
  CMakeLists.txt
  examples/hello_world_loader/CMakeLists.txt
  examples/hello_world_plugin/CMakeLists.txt
  examples/simple_plugin/CMakeLists.txt
  tpe/lib/src/Link.hh
Labels: 🌱 garden

#342 2 to 5
  CMakeLists.txt
Labels: 🏯 fortress

#344 Bumps in garden : ign-physics6
  .github/ci/packages.apt
  CMakeLists.txt
Labels: 🌱 garden
