Repository gazebosim/gz-physics, pull requests merged in 2022-07, with the labels that each got.

#356 ign -> gz Shared Lib Migration : gz-physics
  Migration.md
  dartsim/src/SDFFeatures.cc
  dartsim/worlds/falling.world
  tutorials/04-switching-physics-engines.md
Labels: 🌱 garden, ign to gz

#360 Add more common test and refactor helper class
  bullet/src/EntityManagementFeatures.cc
  test/CMakeLists.txt
  test/common_test/CMakeLists.txt
  test/common_test/basic_test.cc
  test/common_test/construct_empty_world.cc
  test/helpers/CMakeLists.txt
  test/helpers/TestLibLoader.cc
  test/helpers/TestLibLoader.hh
Labels: 🌱 garden

#378 Use GzBullet instead of IgnBullet
  CMakeLists.txt
  bullet/CMakeLists.txt
Labels: 🌱 garden

#375 Added gravity feature to bullet-featherstone
  bullet-featherstone/src/SDFFeatures.cc
  bullet-featherstone/src/WorldFeatures.cc
  bullet-featherstone/src/WorldFeatures.hh
  bullet-featherstone/src/plugin.cc
  test/common_test/CMakeLists.txt
  test/common_test/world_features.cc
  test/common_test/worlds/test.world
Labels: 🌱 garden

#377 Restore CXX_STANDARD export from core library
  src/CMakeLists.txt
Labels: 🌱 garden

#383 ign -> gz Provisional Finale: Source Migration : gz-physics
  Changelog.md
  dartsim/src/CustomHeightmapShape.cc
  dartsim/src/SimulationFeatures.cc
  dartsim/src/SimulationFeatures.hh
Labels: 🌱 garden, ign to gz

#363 Added common test free joint features
  dartsim/src/FreeGroupFeatures_TEST.cc
  test/common_test/CMakeLists.txt
  test/common_test/free_joint_features.cc
  test/common_test/worlds/world_with_nested_model.sdf
  tpe/plugin/src/FreeGroupFeatures_TEST.cc
Labels: Bullet

#386 Ignition -> Gazebo
  README.md
Labels: 🏰 citadel, QA

#376 Improve bullet StepForward feature implementation and added granular test
  bullet-featherstone/src/SimulationFeatures.cc
  bullet-featherstone/src/SimulationFeatures.hh
  bullet/src/SimulationFeatures.cc
  bullet/src/SimulationFeatures.hh
  test/common_test/simulation_features.cc
Labels: Bullet, 🌱 garden

#392 2 ➡️ 5
  README.md
Labels: 🏯 fortress

#390 Change IGN_DESIGNATION to GZ_DESIGNATION
  CMakeLists.txt
  api.md.in
  include/ignition/physics/config.hh.in
  tutorials.md.in
Labels: bug, ign to gz

#393 Fix bullet classic entity management
  bullet/src/Base.hh
  bullet/src/EntityManagementFeatures.cc
  bullet/src/EntityManagementFeatures.hh
  bullet/src/SDFFeatures.cc
Labels: Bullet, 🌱 garden

#391 Merge ign-physics5 ➡️ main
  CMakeLists.txt
  Changelog.md
  README.md
  dartsim/src/Base.hh
  dartsim/src/JointFeatures.cc
  dartsim/src/JointFeatures_TEST.cc
  dartsim/src/SDFFeatures.cc
  dartsim/worlds/joint_constraint.sdf
  include/gz/physics/detail/SpecifyData.hh
  src/SpecifyData_TEST.cc
  test/integration/deprecated_TEST.cc
Labels: enhancement, 🌱 garden

#394 README: fix whitespace
  README.md
Labels: documentation, 🌱 garden

#388 Add code coverage ignore file
  CMakeLists.txt
  coverage.ignore.in
Labels: 🏰 citadel, QA

#396 Merge ign-physics1 ➡️ ign-physics2
  CMakeLists.txt
  api.md.in
  include/ignition/physics/config.hh.in
  tutorials.md.in
Labels: 🏰 citadel

#397 Merge ign-physics2 ➡️ ign-physics5
  CMakeLists.txt
  api.md.in
  coverage.ignore.in
  include/ignition/physics/config.hh.in
  tutorials.md.in
Labels: 🏯 fortress

#395 ABI tweaks to help bullet-featherstone
  include/gz/physics/ForwardStep.hh
  include/gz/physics/FrameID.hh
  include/gz/physics/FrameSemantics.hh
  include/gz/physics/detail/FrameSemantics.hh
Labels: 🌱 garden
