Repository gazebosim/gz-physics, pull requests merged in 2022-01, with the labels that each got.

#322 Add project() to examples
  examples/hello_world_loader/CMakeLists.txt
  examples/hello_world_plugin/CMakeLists.txt
  examples/simple_plugin/CMakeLists.txt
Labels: 🏰 citadel

#318 Backport #312 and #316 to Citadel
  dartsim/include/ignition/physics/dartsim/World.hh
  dartsim/src/CustomFeatures.cc
  dartsim/src/CustomFeatures.hh
  tutorials/05_plugin_loading.md
  tutorials/06-physics-simulation-concepts.md
  tutorials/07-implementing-a-physics-plugin.md
  tutorials/08-implementing-a-custom-feature.md
Labels: documentation, 🏰 citadel

#323 2 ➡️ 4
  dartsim/include/ignition/physics/dartsim/World.hh
  dartsim/src/CustomFeatures.cc
  dartsim/src/CustomFeatures.hh
  examples/hello_world_loader/CMakeLists.txt
  examples/hello_world_plugin/CMakeLists.txt
  examples/simple_plugin/CMakeLists.txt
  tutorials/05_plugin_loading.md
  tutorials/06-physics-simulation-concepts.md
  tutorials/07-implementing-a-physics-plugin.md
  tutorials/08-implementing-a-custom-feature.md
Labels: 🏢 edifice

#324 4 ➡️ 5
  Changelog.md
  dartsim/include/ignition/physics/dartsim/World.hh
  dartsim/src/CustomFeatures.cc
  dartsim/src/CustomFeatures.hh
  examples/hello_world_loader/CMakeLists.txt
  examples/hello_world_plugin/CMakeLists.txt
  examples/simple_plugin/CMakeLists.txt
  tutorials/05_plugin_loading.md
  tutorials/06-physics-simulation-concepts.md
  tutorials/07-implementing-a-physics-plugin.md
  tutorials/08-implementing-a-custom-feature.md
Labels: 🏯 fortress

#325 Fix Apache license version
  dartsim/src/JointFeatures_TEST.cc
  dartsim/src/KinematicsFeatures_TEST.cc
  dartsim/src/LinkFeatures_TEST.cc
  dartsim/src/ShapeFeatures_TEST.cc
  dartsim/src/WorldFeatures_TEST.cc
Labels: 🏯 fortress

#326 Fix Apache license version (backport to citadel)
  dartsim/src/JointFeatures_TEST.cc
  dartsim/src/KinematicsFeatures_TEST.cc
  dartsim/src/LinkFeatures_TEST.cc
  dartsim/src/ShapeFeatures_TEST.cc
Labels: 🏰 citadel

#327 Fix Apache license version (backport to edifice)
  dartsim/src/JointFeatures_TEST.cc
  dartsim/src/KinematicsFeatures_TEST.cc
  dartsim/src/LinkFeatures_TEST.cc
  dartsim/src/ShapeFeatures_TEST.cc
  dartsim/src/WorldFeatures_TEST.cc
Labels: 🏢 edifice
