Repository gazebosim/gz-physics, pull requests merged in 2023-08, with the labels that each got.

#527 Fix Github project automation for new project board
  .github/workflows/triage.yml
Labels: 🌱 garden, 🎵 harmonic

#526 Bumps in harmonic : ci_matching_branch/bump_harmonic_gz-physics7
  .github/ci-focal/before_cmake.sh
  .github/ci/packages-focal.apt
  .github/ci/packages.apt
  .github/workflows/ci.yml
  CMakeLists.txt
  README.md
  test/common_test/free_joint_features.cc
  tutorials/06-physics-simulation-concepts.md
Labels: beta

#515 Minor cleanup of dartsim
  dartsim/src/Base.hh
  dartsim/src/Base_TEST.cc
  dartsim/src/CustomHeightmapShape.cc
  dartsim/src/CustomHeightmapShape.hh
  dartsim/src/EntityManagementFeatures.cc
  dartsim/src/EntityManagementFeatures.hh
  dartsim/src/FreeGroupFeatures.cc
  dartsim/src/JointFeatures.cc
  dartsim/src/JointFeatures.hh
  dartsim/src/SDFFeatures.hh
Labels: beta, 🌱 garden, 🎵 harmonic

#528 Consolidate packages.apt files
  .github/ci/packages-jammy.apt
  .github/ci/packages.apt
Labels: beta

#529 Unregister collision detectors when the darstim plugin is unloaded
  dartsim/src/plugin.cc
Labels: 🌱 garden

#531 Reduce error to debug msg for mesh construction
  dartsim/src/SDFFeatures.cc
Labels: 🎵 harmonic

#532 Merge gz-physics6 ➡️ main
  .github/workflows/triage.yml
  dartsim/src/Base.hh
  dartsim/src/Base_TEST.cc
  dartsim/src/CustomHeightmapShape.cc
  dartsim/src/CustomHeightmapShape.hh
  dartsim/src/EntityManagementFeatures.cc
  dartsim/src/EntityManagementFeatures.hh
  dartsim/src/FreeGroupFeatures.cc
  dartsim/src/JointFeatures.cc
  dartsim/src/JointFeatures.hh
  dartsim/src/SDFFeatures.hh
  dartsim/src/plugin.cc
Labels: 🎵 harmonic

#507 Add optional binary relocatability
  CMakeLists.txt
  dartsim/CMakeLists.txt
  include/gz/physics/InstallationDirectories.hh
  include/gz/physics/config.hh.in
  src/CMakeLists.txt
  src/InstallationDirectories.cc
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/regression/CMakeLists.txt
  tpe/lib/CMakeLists.txt
  tpe/plugin/CMakeLists.txt
Labels: beta, 🌱 garden

#517 Mimic constraint feature using bullet-featherstone
  bullet-featherstone/src/Base.hh
  bullet-featherstone/src/JointFeatures.cc
  bullet-featherstone/src/JointFeatures.hh
  include/gz/physics/Joint.hh
  include/gz/physics/detail/Joint.hh
  test/common_test/CMakeLists.txt
  test/common_test/joint_mimic_features.cc
  test/common_test/worlds/mimic_fast_slow_pendulums_world.sdf
  test/common_test/worlds/mimic_pendulum_world.sdf
  test/common_test/worlds/mimic_prismatic_world.sdf
  test/common_test/worlds/mimic_universal_world.sdf
Labels: beta, 🎵 harmonic

#534 Merge gz-physics6 ➡️ main
  CMakeLists.txt
  Changelog.md
  dartsim/CMakeLists.txt
  include/gz/physics/InstallationDirectories.hh
  include/gz/physics/config.hh.in
  src/CMakeLists.txt
  src/InstallationDirectories.cc
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/regression/CMakeLists.txt
  tpe/lib/CMakeLists.txt
  tpe/plugin/CMakeLists.txt
Labels: 🎵 harmonic

#535 Prepare for 7.0.0~pre2 release
  CMakeLists.txt
Labels: 🎵 harmonic
