Repository gazebosim/gz-physics, pull requests merged in 2023-09, with the labels that each got.

#536 Prepare for 5.3.2 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#537 Fortress: backport fix for dartsim segfaults
  dartsim/src/plugin.cc
Labels: 🏯 fortress

#538 Merge ign-physics5 gz-physics6
  Changelog.md
Labels: 🌱 garden

#539 Cleaning up bullet memory use issues
  bullet-featherstone/src/Base.hh
  bullet-featherstone/src/FreeGroupFeatures.cc
  bullet-featherstone/src/JointFeatures.cc
  bullet-featherstone/src/SDFFeatures.cc
  bullet/src/Base.hh
Labels: 🌱 garden

#543 joint_features test: reduce console spam
  test/common_test/joint_features.cc
Labels: 🌱 garden

#553 Use libdart6.13 packages in CI from packages.o.o
  .github/ci/packages.apt
Labels: 🎵 harmonic

#551 Make dartsim/World.hh header private
  dartsim/CMakeLists.txt
  dartsim/src/AddedMassFeatures_TEST.cc
  dartsim/src/CustomFeatures.hh
  dartsim/src/SDFFeatures_TEST.cc
  dartsim/src/World.hh
Labels: 🎵 harmonic

#552 Prepare for 6.5.1 Release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#555 Prepare for 7.0.0~pre3 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic

#556 dartsim: Fix sign convention error with contact surface motion velocities
  CMakeLists.txt
  dartsim/src/SimulationFeatures.cc
  test/common_test/CMakeLists.txt
  test/common_test/simulation_features.cc
Labels: bug, beta, 🎵 harmonic

#557 Prepare for 7.0.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic
