Repository gazebosim/gz-physics, pull requests merged in 2023-11, with the labels that each got.

#566 Add sample ctest cmds to tutorials
  tutorials/02_installation.md
Labels: 🌱 garden

#562 bullet-featherstone: fix how links are flattened in ConstructSdfModel
  bullet-featherstone/src/SDFFeatures.cc
  test/common_test/world_features.cc
  test/common_test/worlds/world_unsorted_links.sdf
Labels: 🌱 garden

#544 bullet-featherstone: support off-diagonal inertia
  bullet-featherstone/src/SDFFeatures.cc
Labels: Bullet, 🌱 garden

#567 bullet-featherstone: fix setting angular velocity
  bullet-featherstone/src/FreeGroupFeatures.cc
  bullet-featherstone/src/KinematicsFeatures.cc
  test/common_test/simulation_features.cc
Labels: 🌱 garden

#570 Merge gz-physics6 ➡️ gz-physics7
  bullet-featherstone/src/FreeGroupFeatures.cc
  bullet-featherstone/src/JointFeatures.cc
  bullet-featherstone/src/KinematicsFeatures.cc
  bullet-featherstone/src/SDFFeatures.cc
  test/common_test/CMakeLists.txt
  test/common_test/detachable_joint.cc
  test/common_test/simulation_features.cc
  test/common_test/world_features.cc
  test/common_test/worlds/detachable_joint.world
  test/common_test/worlds/world_unsorted_links.sdf
  tutorials/02_installation.md
Labels: 🎵 harmonic

#568 Backport #351 to citadel: fix dartsim inertia matrix rotation
  dartsim/src/SDFFeatures.cc
Labels: 🏰 citadel

#572 Update Github Action workflows
  .github/workflows/ci.yml
  .github/workflows/triage.yml
Labels: 🏰 citadel

#575 Merge ign-physics2 ➡️ ign-physics5
  .github/workflows/ci.yml
  .github/workflows/triage.yml
Labels: 🏯 fortress

#578 CI workflow: use 22.04 for codecheck, coverage
  .github/workflows/ci.yml
Labels: 🌱 garden
