Repository gazebosim/gz-physics, pull requests merged in 2023-01, with the labels that each got.

#465 Fix build errors and warnings for DART 6.13.0
  dartsim/src/Base.hh
  dartsim/src/SimulationFeatures.cc
Labels: 🏰 citadel

#466 Fix build errors and warnings for DART 6.13.0 (Cherry-Pick #465)
  dartsim/src/Base.hh
  dartsim/src/SimulationFeatures.cc
Labels: 🏯 fortress

#467 5 ➡️ 6
  dartsim/src/Base.hh
  dartsim/src/SimulationFeatures.cc
Labels: 🌱 garden

#470 Refactor the VectorApprox to a single location
  dartsim/src/WorldFeatures_TEST.cc
  test/Utils.hh
  test/common_test/addexternalforcetorque.cc
  test/common_test/link_features.cc
  test/common_test/shape_features.cc
  test/common_test/world_features.cc
Labels: 🌱 garden

#468 Prepare for 2.6.1 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#472 Apply ign->gz after forward merge from ign-physics2
  heightmap/include/gz/physics/heightmap/HeightmapShape.hh
  heightmap/include/gz/physics/heightmap/detail/HeightmapShape.hh
  heightmap/include/ignition/physics/heightmap/HeightmapShape.hh
  include/gz/physics/CapsuleShape.hh
  include/gz/physics/EllipsoidShape.hh
  include/gz/physics/Joint.hh
  include/gz/physics/World.hh
  include/gz/physics/detail/CapsuleShape.hh
  include/gz/physics/detail/EllipsoidShape.hh
  include/gz/physics/detail/RelativeQuantity.hh
  include/gz/physics/detail/World.hh
Labels: 🏯 fortress

#473 Fix windows warnings related to bullet
  bullet/src/Base.hh
  bullet/src/SDFFeatures.cc
  bullet/src/plugin.cc
Labels: 🏯 fortress

#474 Prepare for 6.3.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#469 Prepare for 5.3.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#464 Resolve joints in nested models
  dartsim/src/Base.hh
  dartsim/src/Base_TEST.cc
  dartsim/src/EntityManagementFeatures.cc
  dartsim/src/JointFeatures.cc
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures_TEST.cc
Labels: 🌱 garden

#476 Merge ign-physics2 ➡️ ign-physics5
  Changelog.md
Labels: 🏯 fortress
