Repository gazebosim/gz-physics, pull requests merged in 2023-03, with the labels that each got.

#482 Remove an extra symlink on all platforms
  bullet-featherstone/CMakeLists.txt
Labels: 🌱 garden, 🎵 harmonic

#485 Merge ign-physics5 ➡️ gz-physics6
  Changelog.md
  dartsim/src/SDFFeatures.cc
Labels: 🌱 garden, 🎵 harmonic

#487 Rename COPYING to LICENSE
  COPYING
  LICENSE
Labels: 🏰 citadel

#488 CI workflow: use checkout v3
  .github/workflows/ci.yml
Labels: 🏰 citadel

#489 Merge ign-physics2 ➡️ ign-physics5
  .github/workflows/ci.yml
  COPYING
  LICENSE
Labels: 🏯 fortress

#490 CI workflow: use checkout v3
  .github/workflows/ci.yml
Labels: 🏯 fortress

#491 Merge ign-physics5 ➡️ gz-physics6
  .github/workflows/ci.yml
  COPYING
  LICENSE
Labels: 🌱 garden, 🎵 harmonic

#486 Fix a crash due to an invalid pointer
  dartsim/src/SDFFeatures.cc
Labels: 🏰 citadel

#492 Forward port 2 to 5
  dartsim/src/SDFFeatures.cc
Labels: 🌱 garden, 🎵 harmonic

#495 Move joint transmitted wrench test to separate file
  test/common_test/CMakeLists.txt
  test/common_test/joint_features.cc
  test/common_test/joint_transmitted_wrench_features.cc
Labels: 🌱 garden, 🎵 harmonic

#498 Fix joint index used in bookkeeping
  dartsim/CMakeLists.txt
  dartsim/src/Base.hh
  dartsim/src/Base_TEST.cc
Labels: 🌱 garden, 🎵 harmonic

#499 🎈 6.3.2
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden, 🎵 harmonic

#500 dartsim: Refactor entity addition logic in the EntityStorage class
  dartsim/src/Base.hh
Labels: 🌱 garden, 🎵 harmonic
