Repository gazebosim/gz-physics, pull requests merged in 2024-04, with the labels that each got.

#611 [bullet-featherstone] Ignore collision between static objects and objects with world joint
  bullet-featherstone/src/SDFFeatures.cc
  test/common_test/collisions.cc
Labels: 🎵 harmonic

#621 Disable test failing due to ODE/libccd
  test/common_test/joint_features.cc
Labels: 🎵 harmonic

#622 Prepare for 7.2.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic

#615 Revert workaround for homebrew ODE issue
  test/common_test/detachable_joint.cc
Labels: 🎵 harmonic

#619 backport bullet-featherstone default solver iteration setting
  bullet-featherstone/src/Base.cc
Labels: 🎵 harmonic

#624 Merge gz-physics7 ➡️ main
  Changelog.md
  bullet-featherstone/CMakeLists.txt
  bullet-featherstone/src/FreeGroupFeatures.cc
  bullet-featherstone/src/JointFeatures.cc
  bullet-featherstone/src/SDFFeatures.cc
  bullet/CMakeLists.txt
  bullet/src/plugin.cc
  dartsim/CMakeLists.txt
  test/common_test/collisions.cc
  test/common_test/free_joint_features.cc
  test/common_test/joint_features.cc
  test/common_test/worlds/joint_across_models.sdf
  tpe/plugin/CMakeLists.txt
Labels: 🏛️ ionic

#625 Find python directly instead of using GzPython
  test/common_test/CMakeLists.txt
Labels: 🏛️ ionic

#606 bullet-featherstone: Support convex decomposition for meshes
  bullet-featherstone/src/Base.cc
  bullet-featherstone/src/Base.hh
  bullet-featherstone/src/SDFFeatures.cc
  dartsim/src/EntityManagement_TEST.cc
  test/common_test/collisions.cc
  test/include/test/Resources.hh
  test/resources/v_shape.obj
Labels: 🏛️ ionic

#631 Backport bullet-featherstone convex decomposition for meshes (#606)
  bullet-featherstone/src/Base.cc
  bullet-featherstone/src/Base.hh
  bullet-featherstone/src/SDFFeatures.cc
  dartsim/src/EntityManagement_TEST.cc
  test/common_test/collisions.cc
  test/include/test/Resources.hh
  test/resources/v_shape.obj
Labels: 🎵 harmonic

#630 bullet-featurestore: Enable auto deactivation
  bullet-featherstone/src/FreeGroupFeatures.cc
  bullet-featherstone/src/JointFeatures.cc
  bullet-featherstone/src/LinkFeatures.cc
  bullet-featherstone/src/SimulationFeatures.cc
Labels: Bullet, 🎵 harmonic
