Repository gazebosim/gz-physics, pull requests merged in 2024-01, with the labels that each got.

#585 Prepare for 2.6.2 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#588 Remove HIDE_SYMBOLS_BY_DEFAULT: replace by a default configuration in gz-cmake.
  CMakeLists.txt
Labels: 🏛️ ionic

#589 Merge ign-physics2 ➡️ ign-physics5
  Changelog.md
Labels: 🏯 fortress

#591 Get bullet version from cmake instead of API
  test/common_test/CMakeLists.txt
  test/common_test/joint_transmitted_wrench_features.cc
Labels: 🌱 garden

#590 Merge ign-physics5 ➡️ gz-physics6
  .github/workflows/ci.yml
  .github/workflows/triage.yml
  Changelog.md
Labels: 🌱 garden

#592 Merge 6 ➡️ 7
  .github/workflows/ci.yml
  .github/workflows/triage.yml
  Changelog.md
  bullet-featherstone/src/SDFFeatures.cc
  test/common_test/CMakeLists.txt
  test/common_test/joint_transmitted_wrench_features.cc
Labels: 🎵 harmonic

#582 Support setting max contacts in dartsim's ODE collision detector
  dartsim/src/EntityManagementFeatures.cc
  dartsim/src/GzOdeCollisionDetector.cc
  dartsim/src/GzOdeCollisionDetector.hh
  dartsim/src/WorldFeatures.cc
  dartsim/src/WorldFeatures.hh
  include/gz/physics/World.hh
  include/gz/physics/detail/World.hh
  test/common_test/simulation_features.cc
Labels: 🌱 garden

#513 Bazel updates for garden
  BUILD.bazel
  bullet-featherstone/BUILD.bazel
  dartsim/BUILD.bazel
  include/gz/physics/config.hh.in
  src/InstallationDirectories.cc
  test/BUILD.bazel
  test/common_test/CMakeLists.txt
  test/include/test/TestLibLoader.hh
  tpe/plugin/src/SimulationFeatures_TEST.cc
Labels: 🌱 garden
