Repository gazebosim/gz-physics, pull requests merged in 2024-05, with the labels that each got.

#608 Add package.xml
  .github/workflows/package_xml.yml
  package.xml
Labels: 🎵 harmonic

#637 bullet-featherstone: Fix convex hull shape's AABB
  bullet-featherstone/src/SDFFeatures.cc
Labels: 🎵 harmonic

#642 Disable test failing due to ODE/libccd (backport #621)
  dartsim/src/JointFeatures_TEST.cc
Labels: 🏰 citadel

#643 Disable test failing due to ODE/libccd (backport #621)
  dartsim/src/JointFeatures_TEST.cc
Labels: 🏯 fortress

#645 Add missing algorithm include
  include/gz/physics/detail/InspectFeatures.hh
Labels: 🎵 harmonic
