Repository gazebosim/gz-physics, pull requests merged in 2024-02, with the labels that each got.

#596 Revert "Bazel updates for garden"
  BUILD.bazel
  bullet-featherstone/BUILD.bazel
  dartsim/BUILD.bazel
  include/gz/physics/config.hh.in
  src/InstallationDirectories.cc
  test/BUILD.bazel
  test/common_test/CMakeLists.txt
  test/include/test/TestLibLoader.hh
  tpe/plugin/src/SimulationFeatures_TEST.cc
Labels: 🌱 garden

#597 Define GZ_PHYSICS_VERSION_NAMESPACE in config.hh
  include/gz/physics/config.hh.in
Labels: 🏛️ ionic

#601 Require gz-math 6.13 for ign->gz transition
  CMakeLists.txt
Labels: 🏯 fortress
