Repository gazebosim/gz-physics, pull requests merged in 2024-07, with the labels that each got.

#658 bullet-featherstone: Enforce joint velocity and effort limits for velocity control commands
  bullet-featherstone/README.md
  bullet-featherstone/src/Base.hh
  bullet-featherstone/src/JointFeatures.cc
  bullet-featherstone/src/JointFeatures.hh
  bullet-featherstone/src/SDFFeatures.cc
  bullet-featherstone/src/SimulationFeatures.cc
  bullet-featherstone/src/SimulationFeatures.hh
  test/common_test/CMakeLists.txt
  test/common_test/joint_features.cc
  test/common_test/worlds/test.world
Labels: Bullet, 🎵 harmonic

#663 Fix CTAD compile warnings
  bullet-featherstone/src/JointFeatures.cc
Labels: 🎵 harmonic

#665 bullet-featherstone: Support empty links
  bullet-featherstone/src/SDFFeatures.cc
  bullet-featherstone/src/SDFFeatures.hh
  test/common_test/worlds/test.world
Labels: 🎵 harmonic

#669 Merge gz-physics7 ➡️ main: part 1
  .github/workflows/package_xml.yml
  CMakeLists.txt
  bullet-featherstone/src/Base.hh
  bullet-featherstone/src/FreeGroupFeatures.cc
  bullet-featherstone/src/JointFeatures.cc
  bullet-featherstone/src/KinematicsFeatures.cc
  bullet-featherstone/src/KinematicsFeatures.hh
  bullet-featherstone/src/LinkFeatures.cc
  bullet-featherstone/src/SDFFeatures.cc
  bullet-featherstone/src/ShapeFeatures.cc
  bullet-featherstone/src/SimulationFeatures.cc
  dartsim/src/SimulationFeatures.cc
  dartsim/src/SimulationFeatures.hh
  include/gz/physics/GetRayIntersection.hh
  include/gz/physics/detail/GetRayIntersection.hh
  include/gz/physics/detail/InspectFeatures.hh
  package.xml
  test/common_test/CMakeLists.txt
  test/common_test/Worlds.hh
  test/common_test/joint_features.cc
  test/common_test/kinematic_features.cc
  test/common_test/link_features.cc
  test/common_test/simulation_features.cc
  test/common_test/worlds/detachable_joint.world
  test/common_test/worlds/joint_across_models_fixed.sdf
  test/common_test/worlds/pose_offset.sdf
Labels: beta, 🏛️ ionic

#670 Merge gz-physics7 ➡️ main
  Changelog.md
  bullet-featherstone/README.md
  bullet-featherstone/src/Base.hh
  bullet-featherstone/src/JointFeatures.cc
  bullet-featherstone/src/JointFeatures.hh
  bullet-featherstone/src/SDFFeatures.cc
  bullet-featherstone/src/SDFFeatures.hh
  bullet-featherstone/src/SimulationFeatures.cc
  bullet-featherstone/src/SimulationFeatures.hh
  test/common_test/CMakeLists.txt
  test/common_test/joint_features.cc
  test/common_test/worlds/test.world
Labels: beta, 🏛️ ionic

#671 Enable 24.04 CI, require cmake 3.22.1
  .github/workflows/ci.yml
  CMakeLists.txt
  README.md
  examples/hello_world_loader/CMakeLists.txt
  examples/hello_world_plugin/CMakeLists.txt
  examples/simple_plugin/CMakeLists.txt
Labels: 🏛️ ionic
