Repository gazebosim/gz-physics, pull requests merged in 2024-06, with the labels that each got.

#632 bullet-featherstone: Update fixed constraint behavior
  bullet-featherstone/src/Base.hh
  bullet-featherstone/src/FreeGroupFeatures.cc
  bullet-featherstone/src/JointFeatures.cc
  bullet-featherstone/src/SDFFeatures.cc
  test/common_test/CMakeLists.txt
  test/common_test/Worlds.hh
  test/common_test/joint_features.cc
  test/common_test/worlds/joint_across_models_fixed.sdf
Labels: Bullet, 🎵 harmonic

#647 bullet-featherstone: Fix bounding box for collisions with pose offset
  bullet-featherstone/src/KinematicsFeatures.cc
  bullet-featherstone/src/KinematicsFeatures.hh
  bullet-featherstone/src/ShapeFeatures.cc
  test/common_test/Worlds.hh
  test/common_test/kinematic_features.cc
  test/common_test/link_features.cc
  test/common_test/worlds/pose_offset.sdf
Labels: Bullet, 🎵 harmonic

#633 Add no gravity link support
  dartsim/src/SDFFeatures.cc
  dartsim/src/WorldFeatures_TEST.cc
  dartsim/worlds/falling.world
Labels: needs upstream release, 🏯 fortress

#584 Minor optimization for picking contact points in dartsim's ODE collision detector
  dartsim/src/GzOdeCollisionDetector.cc
  test/common_test/Worlds.hh
  test/common_test/simulation_features.cc
  test/common_test/worlds/collision_pair_contact_point.sdf
Labels: 🌱 garden

#641 Ray intersection simulation feature
  CMakeLists.txt
  dartsim/src/SimulationFeatures.cc
  dartsim/src/SimulationFeatures.hh
  include/gz/physics/GetRayIntersection.hh
  include/gz/physics/detail/GetRayIntersection.hh
  test/common_test/simulation_features.cc
Labels: 🎵 harmonic

#639 Add Cone as a collision shape
  README.md
  bullet-featherstone/README.md
  bullet-featherstone/src/SDFFeatures.cc
  bullet-featherstone/src/ShapeFeatures.cc
  bullet-featherstone/src/ShapeFeatures.hh
  bullet/src/SDFFeatures.cc
  dartsim/src/CustomConeMeshShape.cc
  dartsim/src/CustomConeMeshShape.hh
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures_TEST.cc
  dartsim/src/ShapeFeatures.cc
  dartsim/src/ShapeFeatures.hh
  include/gz/physics/ConeShape.hh
  include/gz/physics/detail/ConeShape.hh
  test/common_test/simulation_features.cc
  test/common_test/worlds/shapes.world
  tpe/lib/src/Collision.cc
  tpe/lib/src/Shape.cc
  tpe/lib/src/Shape.hh
  tpe/plugin/src/SDFFeatures.cc
  tpe/plugin/src/ShapeFeatures.cc
  tpe/plugin/src/ShapeFeatures.hh
  tpe/plugin/src/SimulationFeatures_TEST.cc
Labels: 🏛️ ionic

#653 bullet-featherstone: Fix attaching fixed joint between models with inertial pose offset
  bullet-featherstone/src/JointFeatures.cc
  test/common_test/worlds/detachable_joint.world
Labels: 🎵 harmonic

#654 Merge ign-physics2 ➡️ ign-physics5
  .github/CODEOWNERS
Labels: 🏯 fortress

#656 Merge 5 -> 6
  .github/CODEOWNERS
  dartsim/src/SDFFeatures.cc
  test/common_test/world_features.cc
  test/common_test/worlds/falling.world
Labels: 🌱 garden

#655 bullet-featherstone: Parse voxel resolution SDF param when decomposing meshes
  bullet-featherstone/src/SDFFeatures.cc
Labels: 🎵 harmonic

#628 [featherstone] Publish JointFeedback forces.
  bullet-featherstone/src/JointFeatures.cc
Labels: Bullet, 🎵 harmonic

#638 Add Cone as a primitive parametric shape.
  README.md
  bullet-featherstone/README.md
  bullet-featherstone/src/SDFFeatures.cc
  bullet-featherstone/src/ShapeFeatures.cc
  bullet-featherstone/src/ShapeFeatures.hh
  bullet/src/SDFFeatures.cc
  dartsim/src/CustomConeMeshShape.cc
  dartsim/src/CustomConeMeshShape.hh
  dartsim/src/SDFFeatures.cc
  dartsim/src/SDFFeatures_TEST.cc
  dartsim/src/ShapeFeatures.cc
  dartsim/src/ShapeFeatures.hh
  include/gz/physics/ConeShape.hh
  include/gz/physics/detail/ConeShape.hh
  test/common_test/joint_features.cc
  test/common_test/simulation_features.cc
  test/common_test/worlds/shapes.world
  tpe/lib/src/Collision.cc
  tpe/lib/src/Shape.cc
  tpe/lib/src/Shape.hh
  tpe/plugin/src/SDFFeatures.cc
  tpe/plugin/src/ShapeFeatures.cc
  tpe/plugin/src/ShapeFeatures.hh
  tpe/plugin/src/SimulationFeatures_TEST.cc
Labels: 🎵 harmonic

#659 Prepare for 7.3.0
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🎵 harmonic
