Repository gazebosim/gz-physics, pull requests merged in 2024-03, with the labels that each got.

#574 bullet-featherstone: Support nested models
  bullet-featherstone/src/Base.hh
  bullet-featherstone/src/EntityManagementFeatures.cc
  bullet-featherstone/src/EntityManagementFeatures.hh
  bullet-featherstone/src/FreeGroupFeatures.cc
  bullet-featherstone/src/SDFFeatures.cc
  bullet-featherstone/src/SDFFeatures.hh
  test/common_test/CMakeLists.txt
  test/common_test/Worlds.hh
  test/common_test/free_joint_features.cc
  test/common_test/joint_features.cc
  test/common_test/world_features.cc
  test/common_test/worlds/world_single_nested_model.sdf
Labels: 🌱 garden

#600 bullet-featherstone: Improve mesh collision stability
  bullet-featherstone/src/Base.cc
  bullet-featherstone/src/SDFFeatures.cc
  test/common_test/joint_features.cc
Labels: 🌱 garden

#602 Merge 6 -> 7
  bullet-featherstone/src/Base.cc
  bullet-featherstone/src/Base.hh
  bullet-featherstone/src/EntityManagementFeatures.cc
  bullet-featherstone/src/EntityManagementFeatures.hh
  bullet-featherstone/src/FreeGroupFeatures.cc
  bullet-featherstone/src/SDFFeatures.cc
  bullet-featherstone/src/SDFFeatures.hh
  test/common_test/CMakeLists.txt
  test/common_test/Worlds.hh
  test/common_test/free_joint_features.cc
  test/common_test/joint_features.cc
  test/common_test/world_features.cc
  test/common_test/worlds/world_single_nested_model.sdf
Labels: 🎵 harmonic

#605 Remove @mxgrey as code owner
  .github/CODEOWNERS
Labels: 🏰 citadel

#607 Prepare for 7.1.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic

#609 Support setting solver iterations
  bullet-featherstone/src/Base.cc
  bullet-featherstone/src/WorldFeatures.cc
  bullet-featherstone/src/WorldFeatures.hh
  dartsim/src/WorldFeatures.cc
  dartsim/src/WorldFeatures.hh
  dartsim/src/WorldFeatures_TEST.cc
  include/gz/physics/World.hh
  include/gz/physics/detail/World.hh
  test/common_test/joint_features.cc
  test/common_test/world_features.cc
Labels: 🏛️ ionic

#610 [bullet-featherstone] Fix attaching fixed joint
  bullet-featherstone/src/JointFeatures.cc
  test/common_test/joint_features.cc
  test/common_test/worlds/joint_across_models.sdf
Labels: 🎵 harmonic

#613 Disable check in `DetachableJointTest.CorrectAttachmentPoints` test for dartsim plugin on homebrew
  test/common_test/detachable_joint.cc
Labels: 🎵 harmonic
