Repository gazebosim/gz-physics, pull requests merged in 2025-08, with the labels that each got.

#649 bullet-featherstone: Fix model frame data pose
  bullet-featherstone/src/Base.hh
  bullet-featherstone/src/KinematicsFeatures.cc
  bullet-featherstone/src/SDFFeatures.cc
  test/common_test/kinematic_features.cc
  test/common_test/worlds/pose_offset.sdf
Labels: Bullet, 🎵 harmonic

#650 bullet-featherstone: Fix joint frame data pose
  bullet-featherstone/src/Base.hh
  bullet-featherstone/src/KinematicsFeatures.cc
  test/common_test/kinematic_features.cc
Labels: Bullet, 🎵 harmonic

#651 Fix model frame data
  dartsim/src/KinematicsFeatures.cc
  test/common_test/kinematic_features.cc
Labels: 🎵 harmonic

#618 bullet-featherstone: Add Kinematic feature
  bullet-featherstone/src/KinematicLinkFeatures.cc
  bullet-featherstone/src/KinematicLinkFeatures.hh
  bullet-featherstone/src/SDFFeatures.cc
  bullet-featherstone/src/plugin.cc
  include/gz/physics/KinematicLink.hh
  include/gz/physics/detail/KinematicLink.hh
  test/common_test/kinematic_features.cc
Labels: Bullet, 🪵 jetty

#775 Replace main branch with gz-physics9
  .github/workflows/bazel.yml
  README.md
  tutorials/03_physics_plugins.md
  tutorials/05_plugin_loading.md
  tutorials/08-implementing-a-custom-feature.md
  tutorials/09_use_custom_engine.md
Labels: 🪵 jetty

#777 Fix path in physics plugin implementation tutorial
  tutorials/07-implementing-a-physics-plugin.md
Labels: 🪵 jetty

#778 Fix spelling in simulation concepts tutorial
  tutorials/06-physics-simulation-concepts.md
Labels: 🪵 jetty
