Repository gazebosim/gz-physics, pull requests merged in 2025-01, with the labels that each got.

#710 ci.yml: run cppcheck, cpplint on noble
  .github/workflows/ci.yml
Labels: 🏛️ ionic, 🪵 jetty

#711 Visibility fixes for DART on Windows
  dartsim/src/EntityManagementFeatures.hh
  dartsim/src/SDFFeatures.hh
Labels: 🎵 harmonic

#713 bullet-featherstone: Remove joint motor constraint on joint force cmd
  bullet-featherstone/src/JointFeatures.cc
  test/common_test/joint_features.cc
Labels: Bullet, 🏛️ ionic, 🪵 jetty
